name: Release

permissions:
  contents: write
  actions: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update copyright year
        run: |
          CURRENT_YEAR=$(date +%Y)
          sed -i "s/© [0-9]\{4\}/© $CURRENT_YEAR/g" README.md
          sed -i "s/© [0-9]\{4\}/© $CURRENT_YEAR/g" README.zh-CN.md
          
          # Check if any changes were made
          if git diff --quiet; then
            echo "No copyright year updates needed"
          else
            echo "Updated copyright year to $CURRENT_YEAR"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md README.zh-CN.md
            git commit -m "chore: update copyright year to $CURRENT_YEAR"
            git push
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to lts/*
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Package extension
        run: npx vsce package --no-dependencies

      - name: Publish to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --no-dependencies
    
      - name: Publish to Open VSX
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
        run: npx ovsx publish -p $OVSX_TOKEN
