name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to lts/*
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Package vsce extension
        run: npx vsce package --no-dependencies

      - name: Publish vsce extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --no-dependencies
      
      - name: Package ovsx extension
        run: npx ovsx package

      - name: Publish ovsx extension
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
        run: npx ovsx publish -p $OVSX_TOKEN
