name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to lts/*
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            CHANGELOG.md
            README.md
            LICENSE.md
            res/
          retention-days: 1

  publish-vsce:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts

      - name: Package vsce extension
        run: npx vsce package --no-dependencies

      - name: Publish vsce extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --no-dependencies

  publish-ovsx:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts

      - name: Package ovsx extension
        run: npx ovsx package --no-dependencies

      - name: Publish ovsx extension
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
        run: npx ovsx publish --no-dependencies -p process.env.OVSX_TOKEN

